# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ow_XHTt4iIn4Z8257idOrTLErMV0V1wj
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# from openai import AzureOpenAI
# import os

import streamlit as st
from openai import AzureOpenAI

api_key = st.secrets["azure"]["api_key"]
endpoint = st.secrets["azure"]["endpoint"]
deployment_name = st.secrets["azure"]["deployment_name"]

client = AzureOpenAI(api_key=api_key, azure_endpoint=endpoint, api_version=2025-01-01-preview)

deployment_name = "gpt-4o-mini"

#importing the needed libraries
import pandas as pd

#importing the dataset
data =pd.read_csv("/content/drive/MyDrive/postings.csv")
data.head(5)

#Checking the dataset missing value, info
data.info()
data.isna().sum()

#dropping some columns with so many null values
cols_to_drop = [
    'skills_desc',
    'closed_time',
    'posting_domain',
    'application_url'
]

data_clean = data.drop(columns=cols_to_drop)

#filling the columns with numerical  missing data
data_clean['has_salary'] = data_clean['max_salary'].notnull().astype(int)
data_clean['max_salary'] = data_clean['max_salary'].fillna(data_clean['max_salary'].median())
data_clean['min_salary'] = data_clean['min_salary'].fillna(data_clean['min_salary'].median())
data_clean = data_clean.drop(columns=['med_salary'])
data_clean = data_clean.drop(columns=['normalized_salary'])
data_clean = data_clean.drop(columns=['zip_code', 'fips'])
data_clean = data_clean.drop(columns=['company_id'])
data_clean['views'] = data_clean['views'].fillna(0)
data_clean['applies'] = data_clean['applies'].fillna(0)

#filling the categorical data
data_clean['company_name'] = data_clean['company_name'].fillna("Unknown")
data_clean['formatted_experience_level'] = data_clean['formatted_experience_level'].fillna("Not Specified")
data_clean['work_type'] = data_clean['work_type'].fillna("Not Specified")
data_clean['pay_period'] = data_clean['pay_period'].fillna("Unknown")
data_clean['currency'] = data_clean['currency'].fillna("Unknown")
data_clean['compensation_type'] = data_clean['compensation_type'].fillna("Unknown")
data_clean['remote_allowed'] = data_clean['remote_allowed'].fillna(0)

data_clean.isna().sum()

# main agent class
class Agent:
    def __init__(self, name, system_prompt, client, deployment_name):
        self.name = name
        self.system_prompt = system_prompt
        self.client = client
        self.deployment_name = deployment_name

    def run(self, user_input):
        response = self.client.chat.completions.create(
            model=self.deployment_name,   # ⚡ use deployment here
            messages=[
                {"role": "system", "content": self.system_prompt},
                {"role": "user", "content": user_input}
            ],
            max_tokens=1000
        )
        return response.choices[0].message.content

#agent 1 roles: Loads dataset, Cleans data
job_loader_prompt = """
You are a data loader agent.
Your job is to:
- Load dataset
- Clean missing values
- Return summary of dataset
"""

#agent 2 roles: Extract top skills, Frequency analysis
skills_prompt = """
You are a skills analyst.
Identify:
- Top 10 most in-demand skills
- Frequency of each skill
- Skill clusters (AI, Data, Cloud, etc.)
"""

#agent 3 roles:  Predict trends, Identify growing skills
trend_prompt = """
You are a trend forecaster.
Based on the skills:
- Identify emerging skills
- Predict future demand
- Highlight declining skills
"""

#agent 4: roles: Final output
report_prompt = """
You are a report writer.
Generate a structured report with:
- Key insights
- Top skills
- Career recommendations
- Summary
"""

import streamlit as st
#  Streamlit UI
st.title("Job Skills Trend Analyzer")

uploaded_file = st.file_uploader("Upload CSV of job postings", type="csv")

if uploaded_file:
    df = pd.read_csv(uploaded_file)
    st.write("Dataset Preview", df.head())

    if st.button("Run Multi-Agent Analysis"):
        # Initializing the agents
        job_loader = Agent("Job Loader", job_loader_prompt, client, deployment_name)
        skills_agent = Agent("Skills Analyst", skills_prompt, client, deployment_name)
        trend_agent = Agent("Trend Forecaster", trend_prompt, client, deployment_name)
        report_agent = Agent("Report Writer", report_prompt, client, deployment_name)

        with st.spinner("Running analysis..."):
            try:
                data_summary = job_loader.run(df.head(50).to_string())
                skills_output = skills_agent.run(data_summary)
                trend_output = trend_agent.run(skills_output)
                final_report = report_agent.run(trend_output)

                st.subheader("Final Report")
                st.text(final_report)

            except Exception as e:
                st.error(f"Error: {e}")

#installing streamlit
!pip install streamlit pyngrok openai
